@rootURL = http://localhost:5283

###
POST {{rootURL}}/api/Accounts
Accept: application/json
Content-Type: application/json

{
  "Name" : "nodira"
}


###
GET {{rootURL}}/api/Accounts/71538b8e-14d7-481c-aa8d-34f4f78a33a6
Accept: application/json
Content-Type: application/json



