@rootURL = http://localhost:5283

GET {{RESTAPIBankingApplication_HostAddress}}/weatherforecast/
Accept: application/json

###
GET {{rootURL}}/api/account/nadi
Accept: application/json


###
POST {{rootURL}}/api/account/natalie
Content-Type: application/json
